import type { RegionalKaldik } from './types';

export const REGIONAL_KALDIK_PRESETS: RegionalKaldik[] = [
  {
    id: 'riau',
    name: 'Provinsi Riau (Disdik Riau)',
    description: 'Berdasarkan Pedoman Kalender Pendidikan Dinas Pendidikan Provinsi Riau',
    ganjilTags: {
      'Juli-0': 'mpls',
      'Juli-1': 'kbm',
      'September-2': 'sts',
      'Desember-1': 'sas',
      'Desember-2': 'rapor',
      'Desember-3': 'libur',
    },
    genapTags: {
      'Januari-0': 'kbm',
      'Maret-1': 'sts',
      'Maret-3': 'libur',
      'April-0': 'libur',
      'Juni-1': 'sas',
      'Juni-2': 'rapor',
      'Juni-3': 'libur',
    },
  },
  {
    id: 'jabar',
    name: 'Jawa Barat (Disdik Jabar)',
    description: 'Berdasarkan Pedoman Kalender Pendidikan Disdik Provinsi Jawa Barat',
    ganjilTags: {
      'Juli-0': 'mpls',
      'Juli-1': 'kbm',
      'September-2': 'sts',
      'Desember-1': 'sas',
      'Desember-2': 'rapor',
      'Desember-3': 'libur',
    },
    genapTags: {
      'Januari-0': 'kbm',
      'Maret-1': 'sts',
      'Maret-3': 'libur',
      'April-0': 'libur',
      'Juni-1': 'sas',
      'Juni-2': 'rapor',
      'Juni-3': 'libur',
    },
  },
  {
    id: 'dki',
    name: 'DKI Jakarta (Disdik DKI)',
    description: 'Berdasarkan Kalender Pendidikan Dinas Pendidikan Provinsi DKI Jakarta',
    ganjilTags: {
      'Juli-0': 'mpls',
      'September-3': 'sts',
      'Desember-1': 'sas',
      'Desember-2': 'rapor',
      'Desember-3': 'libur',
    },
    genapTags: {
      'Januari-0': 'kbm',
      'Maret-2': 'sts',
      'Maret-3': 'libur',
      'April-0': 'libur',
      'Juni-1': 'sas',
      'Juni-2': 'rapor',
      'Juni-3': 'libur',
    },
  },
  {
    id: 'jateng',
    name: 'Jawa Tengah & DIY',
    description: 'Berdasarkan Pedoman Kaldik Provinsi Jawa Tengah & DI Yogyakarta',
    ganjilTags: {
      'Juli-0': 'mpls',
      'September-2': 'sts',
      'Desember-1': 'sas',
      'Desember-2': 'rapor',
      'Desember-3': 'libur',
    },
    genapTags: {
      'Januari-0': 'kbm',
      'Maret-1': 'sts',
      'Maret-3': 'libur',
      'April-0': 'libur',
      'Juni-1': 'sas',
      'Juni-2': 'rapor',
      'Juni-3': 'libur',
    },
  },
  {
    id: 'jatim',
    name: 'Jawa Timur (Disdik Jatim)',
    description: 'Berdasarkan Pedoman Kalender Pendidikan Provinsi Jawa Timur',
    ganjilTags: {
      'Juli-0': 'mpls',
      'September-2': 'sts',
      'Desember-1': 'sas',
      'Desember-2': 'rapor',
      'Desember-3': 'libur',
    },
    genapTags: {
      'Januari-0': 'kbm',
      'Maret-1': 'sts',
      'Maret-3': 'libur',
      'April-0': 'libur',
      'Juni-1': 'sas',
      'Juni-2': 'rapor',
      'Juni-3': 'libur',
    },
  },
  {
    id: 'kemenag',
    name: 'Kemenag / Madrasah (Nasional)',
    description: 'Kaldik Khusus Madrasah (MI, MTs, MA) Ditjen Pendis Kemenag RI',
    ganjilTags: {
      'Juli-0': 'mpls',
      'September-2': 'sts',
      'November-4': 'sas',
      'Desember-0': 'sas',
      'Desember-1': 'rapor',
      'Desember-2': 'libur',
      'Desember-3': 'libur',
    },
    genapTags: {
      'Januari-0': 'kbm',
      'Maret-1': 'sts',
      'Maret-3': 'libur',
      'April-0': 'libur',
      'Mei-4': 'sas',
      'Juni-0': 'rapor',
      'Juni-1': 'libur',
      'Juni-2': 'libur',
      'Juni-3': 'libur',
    },
  },
  {
    id: 'custom',
    name: 'Kustom / Daerah Lainnya',
    description: 'Atur secara manual pemetaan pekan efektif dan libur sekolah Anda',
    ganjilTags: {
      'Juli-0': 'mpls',
      'September-2': 'sts',
      'Desember-1': 'sas',
      'Desember-2': 'rapor',
      'Desember-3': 'libur',
    },
    genapTags: {
      'Januari-0': 'kbm',
      'Maret-1': 'sts',
      'Maret-3': 'libur',
      'April-0': 'libur',
      'Juni-1': 'sas',
      'Juni-2': 'rapor',
      'Juni-3': 'libur',
    },
  },
];
